### ISSUE TITLE
No backup files, please!

### ISSUE THREAD

**Issue by a115** [liuchengxu/vim-better-default#1]
This is great and I love everything about these defaults EXCEPT that Vim started writing backup files ('~'). How do I stop it from doing that? 

I tried adding these to the end of  my .vimrc:

    set nobackup
    set nowritebackup

but it seems to ignore them now and writes backup files anyway.

**Comment by liuchengxu** [comment]
@a115 Thank you for your feedback! I have added a backup option, which is set no backup as default. Please update vim-better-default.

**Comment by a115** [comment]
This is great, thank you! But I just realised that I don't actually have a problem with 'backup'... I have a problem with 'undofile'. It's my mistake, because I noticed files ending on '~' and thought they are backup files, but they are actually '.un~' files... So, could you make an option for persistent undo as well?

**Comment by liuchengxu** [comment]
I have already added a persistent undo option, which is set on as default. If you don't want it, add this to your .vimrc:

```
let g:vim_better_default_persistent_undo = 0
```

Please update vim-better-default and any feedback is welcome!
