### ISSUE TITLE
Suggestion: remove mapping:  `nnoremap <CR> :`  

### ISSUE THREAD

**Issue by vlaw** [liuchengxu/vim-better-default#13]
```viml
" Quick command mode
        nnoremap <CR> :
```
The problem is, in Location List,  hit `<CR>` make VI  change to Command mode, 
but the default behavior opening the corresponding file is more suitable IMHO. 
After all, <CR> and `:` both hit a key once, makes no big difference. 😁 

I have `nummap` it already, it's not a big problem anyway.

**Comment by liuchengxu** [comment]
Thanks for your suggestion. In my experience, `:` has to hit 2 keys(<kbd>Shift</kbd> + <kbd>:/;</kbd>, I use the default MacBook Pro keyboard), you'll get `;` if you hits <kbd>:/;</kbd> only once. It may relate to the [input method](https://en.wikipedia.org/wiki/Input_method)? I always switch the input method between Chinese and English. If so, I think it's also useful for those having to input other language besides English.

**Comment by vlaw** [comment]
OK,  thanks for your reply.

**Comment by milesrout** [comment]
This is indeed quite a bad idea. A much much better idea is to do `nnoremap ; :` and `nnoremap : ;`.

**Comment by liuchengxu** [comment]
@milesrout Thanks for your engagement. Could you elaborate? If it's merely for the problem @vlaw met, the solution has been found already:

https://github.com/liuchengxu/vim-better-default/blob/82eecbb903c17062ee13134b4d88ef3241979565/plugin/default.vim#L240

Please see https://groups.google.com/forum/#!topic/vim_use/piH7eo9IKhU for more details.
