### ISSUE TITLE
Re-add ugandan fundraising message

### ISSUE THREAD

**Issue by milesrout** [liuchengxu/vim-better-default#17]
If you want any hope of this becoming a new official default configuration for vim - or even something that can be called objectively better - then you need to not disable the opening message.

**Comment by liuchengxu** [comment]
It's an opinioned better-default, which I have never thought that it could be a new official default for vim. *How dare I be so indiscreet in front of the master like [tpope/vim-sensible](https://github.com/tpope/vim-sensible)* :-).
