### ISSUE TITLE
some 'tnoremap' error in Debian

### ISSUE THREAD

**Issue by iyongliang** [liuchengxu/vim-better-default#18]
handle 'xxxx/vim-better-default/plugin/default.vim' error:
no 295 line, not editor command:
tnoremap <Leader>wj <C-W>j

**Comment by iyongliang** [comment]
I check this file, it has comment for "windows", so I delete it temporary in Debian9

**Comment by liuchengxu** [comment]
Should be fixed now. It's for terminal mode particularly.
