### ISSUE TITLE
Variable for tab size?

### ISSUE THREAD

**Issue by joefiorini** [liuchengxu/vim-better-default#19]
Have you thought about introducing a single config variable for `shiftwidth`, `tabstop` & `softtabstop`? Everywhere I work anymore uses 2 spaces, not 4, but would be nice to have a single setting for that instead of 3.

**Comment by liuchengxu** [comment]
Have no plan. You can try this https://github.com/liuchengxu/vim-better-default#how-to-override-the-existing-settings to satisfy your own meed.
