### ISSUE TITLE
Disabling bell

### ISSUE THREAD

**Issue by CptGibbon** [liuchengxu/vim-better-default#5]
Lines 167-169 of __default.vim__ disable visual bell and set t_vb to empty in an attempt to disable bell effects.  I've found that the hardware bell still sounds on error, a fix for this would be to replace lines 168-169 with `set vb t_vb=`

[vim.wikia.com](http://vim.wikia.com/wiki/Disable_beeping) on disabling beeping correctly.

**Comment by liuchengxu** [comment]
Already updated, thanks!
